#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

namespace fs = std::filesystem;

static bool has_reflect_marker(const std::string& text)
{
    static const std::vector<std::string> markers = {
        "Meta(", "META_OBJECT", "MetaExternal("
    };

    for (const auto& marker : markers)
    {
        if (text.find(marker) != std::string::npos)
            return true;
    }
    return false;
}

static bool is_header(const fs::path& p)
{
    auto ext = p.extension().string();
    std::transform(ext.begin(), ext.end(), ext.begin(),
                   [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
    return ext == ".h" || ext == ".hpp" || ext == ".inl";
}

int main(int argc, char** argv)
{
    fs::path root;
    fs::path out;

    for (int i = 1; i < argc; ++i)
    {
        std::string arg = argv[i];
        if (arg == "--root" && i + 1 < argc)
            root = argv[++i];
        else if (arg == "--out" && i + 1 < argc)
            out = argv[++i];
    }

    if (root.empty() || out.empty())
    {
        std::cerr << "Usage: MetaParser --root <repo_root> --out <generated_cpp_path>\n";
        return 2;
    }

    const fs::path runtime_dir = root / "Runtime";
    std::vector<fs::path> headers;

    if (fs::exists(runtime_dir))
    {
        for (const auto& entry : fs::recursive_directory_iterator(runtime_dir))
        {
            if (!entry.is_regular_file())
                continue;

            const auto& p = entry.path();
            if (!is_header(p))
                continue;

            std::ifstream ifs(p, std::ios::binary);
            if (!ifs)
                continue;

            std::string content((std::istreambuf_iterator<char>(ifs)), std::istreambuf_iterator<char>());
            if (has_reflect_marker(content))
                headers.push_back(p);
        }
    }

    std::sort(headers.begin(), headers.end());

    fs::create_directories(out.parent_path());
    std::ofstream ofs(out, std::ios::binary | std::ios::trunc);
    if (!ofs)
    {
        std::cerr << "Failed to open output file: " << out << "\n";
        return 3;
    }

    ofs << "// Auto-generated by Tools/MetaParser (C++ executable)\n";
    ofs << "#include \"Reflection/Meta.h\"\n";
    ofs << "namespace NLS::meta_generated {\n";
    ofs << "void RegisterGeneratedReflection() {}\n";
    ofs << "}\n\n";
    ofs << "// scanned headers:\n";
    for (const auto& h : headers)
    {
        fs::path rel = fs::relative(h, root);
        ofs << "// - " << rel.generic_string() << "\n";
    }

    return 0;
}
