#include "VSCodeConfigurationGenerator.h"

#include <Json/json.hpp>

#include <array>
#include <fstream>
#include <iterator>
#include <system_error>

namespace NLS::Editor::Debug
{
namespace
{
using Json = nlohmann::json;

constexpr std::array<const char*, 4> kReservedConfigurations = {
    "Nullus: C# Scripts",
    // Remove the name generated by older workspaces when regenerating in
    // place. This keeps a project from accumulating duplicate F5 entries.
    "Nullus: Attach C# Scripts",
    "Nullus: Lua Scripts",
    "Nullus: C# + Lua"};

bool IsReserved(std::string_view name)
{
    for (const auto* reserved : kReservedConfigurations)
    {
        if (name == reserved)
            return true;
    }
    return false;
}

Json BuildCSharpConfiguration(
    const std::filesystem::path& projectRoot,
    const std::filesystem::path& projectManifestPath)
{
    Json configuration = {
        {"name", "Nullus: C# Scripts"},
        {"type", "coreclr"},
        {"request", "attach"},
        {"processId", "${command:nullus.resolveEditorProcess}"},
        {"justMyCode", true},
        {"requireExactSource", false},
        {"enableStepFiltering", false},
        {"sourceFileMap", {{projectRoot.string(), projectRoot.string()}}}
    };
    if (!projectManifestPath.empty())
        configuration["nullusProjectManifest"] = projectManifestPath.string();
    return configuration;
}

Json BuildLuaConfiguration(uint16_t luaPandaPort, bool stopOnEntry)
{
#ifdef _WIN32
    constexpr bool pathCaseSensitivity = false;
#else
    constexpr bool pathCaseSensitivity = true;
#endif
    return {
        {"name", "Nullus: Lua Scripts"},
        {"type", "lua"},
        {"request", "launch"},
        {"connectionPort", luaPandaPort},
        {"useCHook", false},
        {"autoPathMode", true},
        {"pathCaseSensitivity", pathCaseSensitivity},
        {"stopOnEntry", stopOnEntry}
    };
}

Json BuildCompoundConfiguration()
{
    return {
        {"name", "Nullus: C# + Lua"},
        {"configurations", {"Nullus: Lua Scripts", "Nullus: C# Scripts"}}
    };
}

bool WriteJson(const std::filesystem::path& path, const Json& value, std::string& error)
{
    std::ofstream output(path, std::ios::binary | std::ios::trunc);
    if (!output)
    {
        error = "Unable to write " + path.string();
        return false;
    }
    output << value.dump(4) << '\n';
    if (!output)
    {
        error = "Unable to flush " + path.string();
        return false;
    }
    return true;
}

// VS Code treats launch.json and extensions.json as JSONC.  Strip comments
// while respecting quoted strings so existing C++ configurations can be
// merged without forcing users to rewrite their workspace files.
std::string StripJsonComments(const std::string& source)
{
    std::string output;
    output.reserve(source.size());
    bool inString = false;
    bool escaped = false;
    bool lineComment = false;
    bool blockComment = false;
    for (size_t index = 0; index < source.size(); ++index)
    {
        const char character = source[index];
        if (lineComment)
        {
            if (character == '\n' || character == '\r')
            {
                lineComment = false;
                output.push_back(character);
            }
            continue;
        }
        if (blockComment)
        {
            if (character == '*' && index + 1 < source.size() && source[index + 1] == '/')
            {
                blockComment = false;
                ++index;
            }
            else if (character == '\n' || character == '\r')
            {
                output.push_back(character);
            }
            continue;
        }
        if (inString)
        {
            output.push_back(character);
            if (escaped)
                escaped = false;
            else if (character == '\\')
                escaped = true;
            else if (character == '"')
                inString = false;
            continue;
        }
        if (character == '"')
        {
            inString = true;
            output.push_back(character);
        }
        else if (character == '/' && index + 1 < source.size() && source[index + 1] == '/')
        {
            lineComment = true;
            ++index;
        }
        else if (character == '/' && index + 1 < source.size() && source[index + 1] == '*')
        {
            blockComment = true;
            ++index;
        }
        else
        {
            output.push_back(character);
        }
    }
    return output;
}

bool ReadJsonc(const std::filesystem::path& path, Json& output)
{
    std::ifstream input(path, std::ios::binary);
    if (!input)
        return false;
    const std::string source{std::istreambuf_iterator<char>(input), std::istreambuf_iterator<char>()};
    output = Json::parse(StripJsonComments(source), nullptr, false);
    return !output.is_discarded();
}
}

VSCodeConfigurationResult GenerateVSCodeConfiguration(
    const std::filesystem::path& projectRoot,
    const std::filesystem::path& visualStudioCodePath,
    uint16_t luaPandaPort,
    bool stopOnEntry,
    const std::filesystem::path& projectManifestPath)
{
    VSCodeConfigurationResult result;
    if (projectRoot.empty())
    {
        result.errorMessage = "Project root is empty.";
        return result;
    }

    // Canonicalization may fail for a newly-created or sandboxed project root.
    // Keep generation usable in that case while still normalizing the path used
    // for sourceFileMap and the .vscode output location.
    std::error_code canonicalError;
    auto normalizedRoot = std::filesystem::weakly_canonical(projectRoot, canonicalError);
    if (canonicalError)
        normalizedRoot = projectRoot.lexically_normal();
    if (normalizedRoot.empty())
    {
        result.errorMessage = "Unable to normalize project root: " + projectRoot.string();
        return result;
    }
    const auto vscodeDirectory = normalizedRoot / ".vscode";
    std::error_code error;
    std::filesystem::create_directories(vscodeDirectory, error);
    if (error)
    {
        result.errorMessage = "Unable to create " + vscodeDirectory.string() + ": " + error.message();
        return result;
    }

    const auto launchPath = vscodeDirectory / "launch.json";
    Json launch = Json::object();
    if (std::filesystem::exists(launchPath))
    {
        if (!ReadJsonc(launchPath, launch) || !launch.is_object())
        {
            result.errorMessage = "Existing .vscode/launch.json is not valid JSONC.";
            return result;
        }
    }
    launch["version"] = launch.value("version", "0.2.0");
    auto configurations = launch.value("configurations", Json::array());
    if (!configurations.is_array())
    {
        result.errorMessage = "Existing launch.json configurations must be an array.";
        return result;
    }
    Json::array_t existing;
    for (const auto& configuration : configurations)
    {
        if (!configuration.is_object() || !IsReserved(configuration.value("name", "")))
            existing.push_back(configuration);
    }
    // Put the project C# attach profile first so a plain F5 in the generated
    // project workspace resolves the Broker instead of launching the native
    // C++ profile that may already exist in the repository workspace.
    Json::array_t merged;
    merged.push_back(BuildCSharpConfiguration(normalizedRoot, projectManifestPath));
    if (luaPandaPort == 0)
    {
        result.errorMessage = "LuaPanda connection port must be non-zero.";
        return result;
    }
    merged.push_back(BuildLuaConfiguration(luaPandaPort, stopOnEntry));
    merged.push_back(BuildCompoundConfiguration());
    merged.insert(merged.end(), existing.begin(), existing.end());
    launch["configurations"] = std::move(merged);
    if (!WriteJson(launchPath, launch, result.errorMessage))
        return result;

    const auto extensionsPath = vscodeDirectory / "extensions.json";
    Json extensions = Json::object();
    if (std::filesystem::exists(extensionsPath))
    {
        if (!ReadJsonc(extensionsPath, extensions) || !extensions.is_object())
        {
            result.errorMessage = "Existing .vscode/extensions.json is not valid JSONC.";
            return result;
        }
    }
    auto recommendations = extensions.value("recommendations", Json::array());
    if (!recommendations.is_array())
    {
        result.errorMessage = "Existing extensions.json recommendations must be an array.";
        return result;
    }
    const auto addRecommendation = [&recommendations](const char* value)
    {
        for (const auto& item : recommendations)
        {
            if (item.is_string() && item.get<std::string>() == value)
                return;
        }
        recommendations.push_back(value);
    };
    addRecommendation("ms-dotnettools.csdevkit");
    addRecommendation("ms-dotnettools.csharp");
    // This extension is shipped with Nullus. It resolves the project-scoped
    // Broker PID for coreclr attach without using the process picker or PATH.
    addRecommendation("nullus.nullus-script-debugger");
    addRecommendation("stuartwang.luapanda@3.3.1");
    extensions["recommendations"] = std::move(recommendations);
    if (!WriteJson(extensionsPath, extensions, result.errorMessage))
        return result;

    (void)visualStudioCodePath;
    result.success = true;
    return result;
}
}
