name: Build Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [debug, release]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install system build dependencies
        run: |
          sudo apt update
          sudo apt-get install -y \
            build-essential cmake ninja-build pkg-config \
            libwayland-dev wayland-protocols \
            libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libxfixes-dev libxkbcommon-dev \
            libgl1-mesa-dev libglu1-mesa-dev libvulkan-dev

      - name: Build
        run: ./build_linux.sh ${{ matrix.configuration }}
