name: Build MacOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        configuration: [debug, release]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: ./build_macos.sh ${{ matrix.configuration }}

      - name: Run unit tests
        run: ctest --test-dir build -C ${{ matrix.configuration }} --output-on-failure
