name: Build Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [debug, release]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Install dependencies
        run: |
            sudo apt install libwayland-dev libxkbcommon-dev xorg-dev
            sudo apt install libvulkan-dev
            sudo apt-get install libgl1-mesa-dev
      - name: Build
        run: ./build_linux.sh ${{matrix.configuration}} 